### ISSUE TITLE
ENH: Move Arduino hardware files into known position in repo

### ISSUE THREAD

**Issue by jschrempp** [BobGlicksman/LoRa_experiments#26]
I would like to work on the ATmega code in-place in the repo. This requires the /hardware folder tree to be in the repo somewhere. Let's discuss the best place to put this. I want to avoid having to copy code into another location to be able to burn it to the ATmega

**Comment by BobGlicksman** [comment]
When I started working with the Arduino IDE, I just did a "save as" into a file in my local github repo.  Now, all of the changes are in github.  Of course, I need to push the changes to the cloud when I am ready to release.  And of course, I try to work in a branch until we agree to merge the new code into main.  But the point here is that you don't have to copy your Arduino IDE work out of your sketchbook and into github -- you can save to your local repo directly.
